//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainResversationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int Cancel_id { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public string PassengerName { get; set; }
        public Nullable<int> TrainNo { get; set; }
        public string Class { get; set; }
        public System.DateTime Cancel_Date { get; set; }
        public Nullable<int> No_of_Seats { get; set; }
        public Nullable<int> Refund { get; set; }
        public string Remarks { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Train Train { get; set; }
    }
}
