//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking()
        {
            this.cancellations = new HashSet<cancellation>();
        }
    
        public int Booking_ID { get; set; }
        public string PassengerName { get; set; }
        public Nullable<int> TrainNo { get; set; }
        public string Class { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime Date_of_Travel { get; set; }
        public Nullable<int> Totalseats { get; set; }
        public Nullable<double> Totalamount { get; set; }
        public string Status { get; set; }
    
        public virtual Train Train { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cancellation> cancellations { get; set; }
    }
}
